[project]
name = "ansible-role-podman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "ansible-dev-tools>=25.8.3",
]
