---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create container network
      containers.podman.podman_network:
        name: molecule
        state: present

    - name: Create test containers
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command | default(omit) }}"
        privileged: "{{ item.privileged | default(omit) }}"
        state: started
        network:
          - name: molecule
      loop: "{{ molecule_yml.platforms }}"