---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify Podman package is installed on Debian
      ansible.builtin.assert:
        that:
          - "'podman' in ansible_facts.packages"
      when: ansible_os_family == 'Debian'

    - name: Verify podman.socket is running and enabled on Debian
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['podman.socket'].state == 'running'"
          - "ansible_facts.services['podman.socket'].status == 'enabled'"
      when: ansible_os_family == 'Debian'

    - name: Verify Podman package is installed on RHEL
      ansible.builtin.assert:
        that:
          - "'podman' in ansible_facts.packages"
      when: ansible_os_family == 'RedHat'

    - name: Verify podman.socket is running and enabled on RHEL
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['podman.socket'].state == 'running'"
          - "ansible_facts.services['podman.socket'].status == 'enabled'"
      when: ansible_os_family == 'RedHat'

    - name: Verify Podman package is installed on Archlinux
      ansible.builtin.assert:
        that:
          - "'podman' in ansible_facts.packages"
      when: ansible_os_family == 'Archlinux'

    - name: Verify podman.socket is running and enabled on Archlinux
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['podman.socket'].state == 'running'"
          - "ansible_facts.services['podman.socket'].status == 'enabled'"
      when: ansible_os_family == 'Archlinux'

    - name: Verify registries.search configuration
      ansible.builtin.ini:
        path: /etc/containers/registries.conf
        section: registries.search
        option: registries
        value: "{{ registries_search | to_json }}"
        state: present
      check_mode: true
      register: search_check
      failed_when: search_check.changed

    - name: Verify registries.insecure configuration
      ansible.builtin.ini:
        path: /etc/containers/registries.conf
        section: registries.insecure
        option: registries
        value: "{{ registries_insecure | to_json }}"
        state: present
      check_mode: true
      register: insecure_check
      failed_when: insecure_check.changed

    - name: Verify registries.block configuration
      ansible.builtin.ini:
        path: /etc/containers/registries.conf
        section: registries.block
        option: registries
        value: "{{ registries_block | to_json }}"
        state: present
      check_mode: true
      register: block_check
      failed_when: block_check.changed
